apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  # type: NodePort
  ports:
  - protocol: TCP
    name: web
    port: 80
    targetPort: 8080
  # - protocol: TCP
  #   port: 8080
  #   name: admin

