apiVersion: v1
kind: Service
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  # type: NodePort
  ports:
  # - name: http
  #   port: 80
  #   targetPort: 80
  - name: web
    port: 80
    targetPort: 8080
